[libraries]
asciidoctorj = { module="org.asciidoctor:asciidoctorj", version = "3.0.0" }
junit-bom = { module="org.junit:junit-bom", version = "5.10.0" }

[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.3" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }
